project_id = "uyonjhjgmwbisocdedtw"

[functions.sendPush]
verify_jwt = false

[functions.delete_travel]
enabled = true
verify_jwt = true
import_map = "./functions/delete_travel/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/delete_travel/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/delete_travel/*.html" ]

[functions.geocode_city]
enabled = true
verify_jwt = true
import_map = "./functions/geocode_city/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/geocode_city/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/geocode_city/*.html" ]

[functions.delete-user]
enabled = true
verify_jwt = true
import_map = "./functions/delete-user/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/delete-user/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/delete-user/*.html" ]
