name: travel_memoir
description: Travel Memoir project.

publish_to: 'none'

version: 1.0.0+15

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^3.6.0
  firebase_messaging: ^15.2.10

  # HTML íŒŒì‹±
  flutter_html: ^3.0.0-alpha.6

  # UI/ê¸°ë³¸ ìœ í‹¸
  overlay_support: ^2.1.0
  cupertino_icons: ^1.0.2
  url_launcher: ^6.3.2
  shared_preferences: ^2.2.2

  # Supabase
  supabase_flutter: ^2.5.6

  # ì´ë¯¸ì§€/íŒŒì¼ ì²˜ë¦¬
  cached_network_image: ^3.3.1
  path_provider: ^2.1.2
  permission_handler: ^11.0.1

  # HTTP í†µì‹ 
  http: ^1.1.0

  # ì•± ì•„ì´ì½˜
  flutter_launcher_icons: ^0.14.4

  # ë¡œê·¸ì¸
  kakao_flutter_sdk_user: ^1.9.6
  sign_in_with_apple: ^6.1.0
  google_sign_in: ^6.2.1

  share_plus: ^10.0.0
  mapbox_maps_flutter: ^2.4.0
  latlong2: ^0.8.1
 
  flutter_slidable: ^3.1.0
  fl_chart: ^0.66.2
  scrollable_clean_calendar: ^1.5.0
  intl: ^0.20.2
  gal: ^2.3.2
  google_mobile_ads: ^7.0.0  
  introduction_screen: ^4.0.0
  easy_localization: ^3.0.8
  lottie: ^3.1.2
  purchases_flutter: ^8.2.0 
  flutter_native_splash: ^2.4.7
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  image_picker: ^1.1.2

dependency_overrides:
  flutter_math_fork: ^0.6.0
  win32: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/geo/processed/
    - assets/geo/raw/
    - assets/translations/
    - assets/lottie/
     
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  
flutter_native_splash:
  color: "#FFFFFF" # ë°°ê²½ìƒ‰ (í°ìƒ‰ì´ ë¬´ë‚œí•©ë‹ˆë‹¤)
  image: assets/images/splash.png # ðŸ‘ˆ ë¡œë”© í™”ë©´ì— ë„ìš¸ ì´ë¯¸ì§€ ê²½ë¡œ
  fullscreen: true
  ios: true
  android_12:
    image: assets/images/splash.png
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"  


