name: travel_memoir
description: Travel Memoir project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTML 파싱
  flutter_html: ^3.0.0-alpha.6

  # UI/기본 유틸
  overlay_support: ^2.1.0
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2

  # Supabase
  supabase_flutter: ^2.5.6

  # 이미지/파일 처리
  cached_network_image: ^3.3.1
  path_provider: ^2.1.2
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.0.1

  # HTTP 통신
  http: ^1.1.0

  # 앱 아이콘
  flutter_launcher_icons: ^0.14.4

  # 로그인
  kakao_flutter_sdk_user: ^1.9.6
  sign_in_with_apple: ^6.1.0
  google_sign_in: ^6.2.1

  share_plus: ^10.0.0
  mapbox_maps_flutter: ^2.4.0
  latlong2: ^0.8.1
 
  flutter_slidable: ^3.1.0
  image_cropper: ^5.0.1
  fl_chart: ^0.66.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  
dependency_overrides:
  flutter_math_fork: ^0.6.0
  win32: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/geo/processed/
    - assets/geo/raw/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
