name: travel_memoir
description: Travel Memoir project.

publish_to: 'none'

version: 1.0.0+38

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^3.6.0 
  firebase_messaging: ^15.2.10

  # HTML íŒŒì‹±
  flutter_html: ^3.0.0-alpha.6

  # UI/ê¸°ë³¸ ìœ í‹¸
  overlay_support: ^2.1.0
  cupertino_icons: ^1.0.2
  url_launcher: ^6.3.2
  shared_preferences: ^2.2.2

  # Supabase
  supabase_flutter: ^2.5.6

  # ì´ë¯¸ì§€/íŒŒì¼ ì²˜ë¦¬
  cached_network_image: ^3.3.1
  path_provider: ^2.1.2
  permission_handler: ^11.0.1

  # âœ… ì´ë¯¸ì§€ ì••ì¶•ì„ ìœ„í•œ í•„ìˆ˜ ë¼ì´ë¸ŒëŸ¬ë¦¬
  flutter_image_compress: ^2.3.0
  
  # HTTP í†µì‹ 
  http: ^1.1.0

  # ì•± ì•„ì´ì½˜
  flutter_launcher_icons: ^0.14.4

  # ë¡œê·¸ì¸
  kakao_flutter_sdk_user: ^1.9.6
  sign_in_with_apple: ^6.1.0
  google_sign_in: ^6.2.1

  share_plus: ^10.0.0
  mapbox_maps_flutter: ^2.4.0
  latlong2: ^0.8.1
 
  flutter_slidable: ^3.1.0
  fl_chart: ^0.66.2
  scrollable_clean_calendar: ^1.5.0
  intl: ^0.20.2
  gal: ^2.3.2
  google_mobile_ads: ^7.0.0  
  introduction_screen: ^4.0.0
  easy_localization: ^3.0.8
  lottie: ^3.1.2
  purchases_flutter: ^8.2.0 
  flutter_native_splash: ^2.4.7
  flutter_local_notifications: ^19.5.0
  connectivity_plus: ^7.0.0
  flutter_app_badge_control: ^0.0.2
  google_fonts: ^8.0.0
  image: ^4.1.3
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  image_picker: ^1.1.2

dependency_overrides:
  flutter_math_fork: ^0.6.0
  win32: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/geo/processed/
    - assets/geo/raw/
    - assets/translations/
    - assets/lottie/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSansKR-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSansKR-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansKR-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansKR-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansKR-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSansKR-Black.ttf
          weight: 900
  
     
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  # ðŸŽ¯ ì´ ì„¤ì •ë“¤ì´ ì•ˆë“œë¡œì´ë“œ ì°Œê·¸ëŸ¬ì§ì„ ë°©ì§€í•´!
  android_gravity: center 
  fullscreen: false 

  android_12:
    image: assets/images/splash.png
    icon_background_color: "#FFFFFF"
    # ì•ˆë“œë¡œì´ë“œ 12ëŠ” ì´ ì„¤ì •ì„ íŠ¹ížˆ ì¤‘ìš”í•˜ê²Œ ë´
    image_dark: assets/images/splash.png