name: my_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTML 파싱 최신 버전
  flutter_html: ^3.0.0-alpha.6

  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.5.6
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  flutter_math_fork: ^0.6.0
  win32: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

  