name: travel_memoir
description: Travel Memoir project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTML 파싱
  flutter_html: ^3.0.0-alpha.6

  # UI/기본 유틸
  overlay_support: ^2.1.0
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2

  # Supabase
  supabase_flutter: ^2.5.6

  # 이미지/파일 처리
  cached_network_image: ^3.3.1
  path_provider: ^2.1.2
  image_gallery_saver: ^2.0.3

  # HTTP 통신
  http: ^1.1.0

  # 앱 아이콘
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  
dependency_overrides:
  flutter_math_fork: ^0.6.0
  win32: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
